"""Optimize for postgres

Revision ID: fcdff7c3f12a
Revises: ae3f02bb6927
Create Date: 2025-02-06 20:14:20.153356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcdff7c3f12a'
down_revision = 'ae3f02bb6927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('remarks_json',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('previous_reg_json',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.alter_column('previous_reg_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('remarks_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('delivery_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
